FROM php:8.2-apache

LABEL manteiner="Pablo De Jesús <pablo.24726@gmail.com>"

# Update and install basic programs and modules
RUN apt-get update ; \
	apt-get install -y --no-install-recommends \
		vim \
		nano \
		curl \
	; \
	apt-get install -y --no-install-recommends \
		libbz2-dev \
		libgd-dev \
		libgmp-dev \
		libjpeg-dev \
		libldap2-dev \
		libmcrypt-dev \
		libmemcached-dev \
		libmemcached11 \
		libpng-dev \
		libpq-dev \
		libzip-dev \
	; \
	a2enmod rewrite ; \
	# INSTALL PHP
	docker-php-ext-configure gd \
		--with-freetype \
		--with-jpeg \
	; \
	docker-php-ext-install -j$(nproc) \
		# Image
		gd \
		# database
		mysqli \
		pdo \
		pdo_mysql \
		# compression
		zip \
		bz2 \
		# math
		gmp \
		# cache
		opcache \
		# others
		calendar \
		ctype \
		fileinfo \
		iconv \
		json \
		phar \
		soap \
		sockets \
		sysvmsg \
		sysvsem \
		sysvshm \
		tokenizer \
		xml \
		xmlwriter \
	; \
	# PECL
	pecl install \
		apcu-5.1.22 \
		memcached-3.1.5 \
	; \
	# Install XDebug, but not enable by default. Enable using:
	# * php -d$XDEBUG_EXT vendor/bin/phpunit
	# * php_xdebug vendor/bin/phpunit
	pecl install xdebug-3.2.0 ; \
    docker-php-ext-enable xdebug ; \
	# Add development php.ini file
	cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini ; \
	# Enable Virtualhost
	a2ensite 000-default.conf ; \
	# a2ensite default-ssl.conf ; \
	# Clear cache
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* /var/cache/*
